name: Bible search Tests

on: 
  push

jobs:
  cross-browser:
    runs-on: ubuntu-latest
    container: cypress/included:3.8.3
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Chrome browser tests
        run: npx cypress run --browser chrome --spec ./cypress/integration/bible-search-tests.js
