name: Bible search Tests

on: 
  push

jobs:
  cross-browser:
    runs-on: ubuntu-latest
    container: cypress/included:3.8.3
    steps:
      - uses: actions/checkout@v1
      - run: cypress run

      
