
name: Create Cypress report
on:
  push:
    branches:
      - 'master'

jobs:
  cypress-e2e-chrome89:
    name: Run on Chrome 89
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.16.1-chrome80-ff73
    steps:
    - uses: actions/checkout@v1
      with: 
        submodules: true


    - name: Install a project with a clean slate
      run: |
        npx ci

    #- name: Run chrome tests
      #run: npx cypress run --browser chrome --spec ./cypress/integration/bible-search-tests.js
      #continue-on-error: false

    - name: Run firefox tests
      run: npx cypress run --browser firefox --spec ./cypress/integration/bible-search-tests.js
      continue-on-error: false  


    - name: Copy test execution videos 
      run: |
        mkdir public
        cp -r cypress/videos public/videos

    - name: Merge test results into one
      run: npm run report:merge

    - name: Generate HTML report
      run: npm run report:generate

    - name: Deploy report page
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
                